{% set version = "0.1.5" %}

package:
  name: kececifractals
  version: {{ version }}

source:
  path: .  # Derlemeyi bu meta.yaml dosyasının bulunduğu dizinden yap
  url: https://files.pythonhosted.org/packages/75/92/f2f47925b3a2fa03419c74ef6180f864694f97a2972b7ff721f2d6a9fbb4/kececifractals-0.1.5.tar.gz
  sha256: a86f2b83d9031c274595a9518ce39fadc261294c615adbf68db96026585419ba

build:
  noarch: python  # Platformdan bağımsız bir paket oluşturur
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
  number: 0
  entry_points:
    - kececifractals = kececifractals.__main__:main

requirements:
  host:
    - python {{ python }}
    - numpy
    # Other build tools
  run:
    - python >=3.10
    - numpy
    # Other runtime dependencies
  build:
    - python >=3.10
    - pip

test:
  imports:
    - kececifractals

about:
  home: https://github.com/WhiteSymmetry/kececifractals
  license: MIT
  summary: 'Keçeci Fractals: Keçeci-style circle fractal.'
  description: |
    Keçeci Fractals: Keçeci-style circle fractal.
  dev_url: https://github.com/WhiteSymmetry/kececifractals
  doc_url: https://github.com/WhiteSymmetry/kececifractals
  doc_source_url: https://github.com/WhiteSymmetry/kececifractals/blob/main/README.md
